#!/bin/bash

# Desabilitar IPv6
echo "Desabilitando IPv6..."
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
sysctl -p

# Resetar as regras do iptables
echo "Resetando regras do iptables..."
iptables -F
iptables -t nat -F
iptables -t mangle -F

# Políticas padrão
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

# Permitir tráfego de loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Permitir tráfego estabelecido e relacionado
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Permitir tráfego HTTP e HTTPS
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT

# Permitir DNS over HTTPS (dnscrypt-proxy)
iptables -A OUTPUT -p tcp --dport 8888 -j ACCEPT
iptables -A OUTPUT -p udp --dport 853 -j ACCEPT

# Bloquear portas 53 e 5353
iptables -A INPUT -p udp --dport 53 -j DROP
iptables -A INPUT -p tcp --dport 53 -j DROP
iptables -A INPUT -p udp --dport 5353 -j DROP
iptables -A INPUT -p tcp --dport 5353 -j DROP

# Salvar as regras
iptables-save > /etc/iptables/rules.v4

echo "Configuração do firewall concluída."
