#!/bin/bash

systemctl start NetworkManager
sleep 7

pkill dnscrypt-proxy
pkill encrypted-dns
pkill macchange

echo "MastersUniverse" > /etc/hostname
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 127.0.0.1" >> /etc/resolv.conf
echo "nameserver 127.0.2.1" >> /etc/resolv.conf

./firewall-start

nohup /etc/dnscrypt-proxy/macchange.sh &

nohup encrypted-dns -c /etc/dnscrypt-proxy/encrypted-dns.toml &

nohup /etc/dnscrypt-proxy/dnscrypt-proxy &

echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 127.0.0.1" >> /etc/resolv.conf
echo "nameserver 127.0.2.1" >> /etc/resolv.conf

trap stop_server_and_clients SIGINT

tail -f nohup.out
